# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "031dded9ff0ace59248bef0e5f8c4bcb"
name = "Recomedation-SNS"
handle = "recomedation-sns"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content, unauthenticated_read_product_listings, unauthenticated_read_product_tags, unauthenticated_read_product_inventory,write_products,write_orders,write_customers,write_files,read_discounts,write_draft_orders,write_inventory,write_publications"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[[extensions.metafields.read]]
namespace = "custom"
key = "recommendation"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = false